### ISSUE TITLE
Support for Sharp icons

### ISSUE THREAD

**Issue by nemmel2000** [aerni/statamic-font-awesome#13]
Is it possible to select Sharp icons? We use a kit that includes them but they are not selectable. Is this supported? and if its not could it be added?

**Comment by aerni** [comment]
This is currently not possible. Font Awesome changed their API. The integration this addon uses is deprecated. To add the sharp icon styles, the addon has to be updated to use the new API first.

**Comment by aerni** [comment]
Added support for sharp icons with PR https://github.com/aerni/statamic-font-awesome/pull/17.
