### ISSUE TITLE
500 (Internal Server Error) errors in Console when browsing Statamic control panel. Additionally, Fieldtypes screen does not get populated

### ISSUE THREAD

**Issue by ghost** [aerni/statamic-font-awesome#18]
**Environment**
Statamic: 4.5.0 (clean install, default content)
Statamic addons installed: Font Awesome 2.0.0
PHP 8.1.11 (Windows)
Laravel 9.52.5
Google Chrome 114.0.5735.45 (Official Build) (64-bit)
Microsoft Edge 113.0.1774.35 (Official build) (64-bit)

Console errors when navigating Statamic cp: lines 1-74 from attached log
Console errors when trying to add a new field: lines 75-130 from attached log

[statamic4.test-1685809702558.log](https://github.com/aerni/statamic-font-awesome/files/11643212/statamic4.test-1685809702558.log)

![statamic4-font-awesome](https://github.com/aerni/statamic-font-awesome/assets/773715/53735c56-9d98-48f0-88f5-670917f12e5e)

**Comment by aerni** [comment]
I can't reproduce your issue. What does your `storage/logs/laravel.log` say?

**Comment by ghost** [comment]
HI, Michael, log attached, thank you.
[laravel-log-font-awesome.txt](https://github.com/aerni/statamic-font-awesome/files/11644254/laravel-log-font-awesome.txt)

**Comment by aerni** [comment]
I can't make much of this log. Did you configure your [API and Kit Token](https://github.com/aerni/statamic-font-awesome#configuration)?

**Comment by ghost** [comment]
Yes, in .env file.

**Comment by aerni** [comment]
Did you clear the cache? Is this a new installation or updating an existing site? Have you used this addon with an older version before?

**Comment by ghost** [comment]
Cleared cache both in Statamic cp and cli. New installation, fresh Statamic latest version and just the Font Awesome addon. Initially I have seen this behavior in a site with Peak starter kit, but it also manifested on a clean install.

**Comment by aerni** [comment]
I just tried again. Fresh installation of Statamic with the CLI and installing the latest version of the addon. I can't reproduce this issue. It might be a problem with your dev environment. Feel free to create a repo with an installation that reproduces the issue so I can give it a try on my machine. But I doubt that this is an issue with the addon.

**Comment by ghost** [comment]
Got same results on a fresh install on Laravel 10 and 8.1.2-1ubuntu2.11. I have removed the Font Awesome kit and create another one, now everything is good. The only problem I can think of is that old kit had a dot in the name.
