### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by stvnthomas** [aerni/statamic-font-awesome#2]
Thanks for this addon!

Ran into a small issue when installing the package. The following error is thrown during composer install/package discovery:

```
Aerni\FontAwesome\FontAwesome::authToken(): Return value must be of type string, null returned
at vendor/aerni/font-awesome/src/FontAwesome.php:88
```

It looks like it's trying to authenticate with Font Awesome before the package has been configured with the tokens. Works perfect if they're set up in .env and config/font-awesome.php before running composer require.

**Comment by aerni** [comment]
Thanks for the hint. Just fixed it with [v1.0.1](https://github.com/aerni/statamic-font-awesome/releases/tag/v1.0.1).

**Comment by jtphelan** [comment]
I'm getting this same error on a new install. I have the variables set in my .env and the config published. Any ideas?

**Comment by aerni** [comment]
I can't reproduce this. I just whipped up a fresh installation with `statamic new test` and then `composer require aerni/font-awesome`. No error. Do you have more details to share?

**Comment by jtphelan** [comment]
Well I don't know. I just tried it again and it worked fine this time. Not sure what I did wrong.
