### ISSUE TITLE
Missing icons in control panel.

### ISSUE THREAD

**Issue by icemancast** [aerni/statamic-font-awesome#21]
Icons are missing in selection. I have the pro version of font awesome.

Statamic 4.3.0

So it's only for classic which I use 6 is there a way to omit classic from the list or denote the version of Font awesome?

<img width="956" alt="Screenshot 2023-10-28 at 11 37 11 AM" src="https://github.com/aerni/statamic-font-awesome/assets/110063/7fa31516-b9cc-4103-8d5c-bc2361354ce9">

**Comment by aerni** [comment]
I don't understand your question. What icons are missing?

By default, the icons of all families are selectable. If you want to limit the icon families, you can change the selection in the fieldtype's config.
