### ISSUE TITLE
Addon throwing error after update

### ISSUE THREAD

**Issue by sstottelaar** [aerni/statamic-font-awesome#22]
Hi,

First of all, thanks for creating this addon.

Today I updated my Statamic to the latest version and noticed that the addon stopped working. I reverted this upgrade, but I can't get it to work again. In the back-office, I get this error:

```
exception
: 
"ErrorException"
file
: 
"/Users/***/Projects/***/vendor/aerni/font-awesome/src/FontAwesome.php"
line
: 
65
message
: 
"Undefined array key \"data\""
```

I double-checked my API and kit key, but they seem to be fine (and I haven't changed anything on that end).

My setup:

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.32.0 PRO

Statamic Addons
aerni/font-awesome: 2.0.0
doefom/currency-fieldtype: 1.2.2
doublethreedigital/simple-commerce: 5.6.2
mattrothenberg/statamic-mapbox-address: 0.7.4
withcandour/aardvark-seo: 3.0.0

Environment
Laravel Version: 10.25.2
PHP Version: 8.2.11
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Any thoughts what could be wrong?

**Comment by sstottelaar** [comment]
Update: I've tried a fresh installation with the same API and kit key, no issues there. So it's an issue on my dev/prod environment. I've narrowed it down to where the error is thrown, it is this piece of code:

```
$response = Http::post('https://api.fontawesome.com', [
    'query' => $this->iconsQuery(),
])->json()['data']['release']['icons'];
```

I did tweak some settings with static caching on my local and prod environment. On my local machine, it's all disabled, as I've reverted it all.

Any ideas what I could be doing wrong?

**Comment by sstottelaar** [comment]
After some more digging I got this error which comes from the Font Awesome GraphQL API:

```
array:1 [ // vendor/aerni/font-awesome/src/FontAwesome.php:71
  "errors" => array:3 [
    0 => array:2 [
      "message" => "Field icons is too complex: complexity is 86503 and maximum is 50000"
      "locations" => array:1 [
        0 => array:2 [
          "line" => 3
          "column" => 21
        ]
      ]
    ]
    1 => array:2 [
      "message" => "Field release is too complex: complexity is 86504 and maximum is 50000"
      "locations" => array:1 [
        0 => array:2 [
          "line" => 2
          "column" => 17
        ]
      ]
    ]
    2 => array:2 [
      "message" => "Operation is too complex: complexity is 86504 and maximum is 50000"
      "locations" => array:1 [
        0 => array:2 [
          "line" => 1
          "column" => 1
        ]
      ]
    ]
  ]
]
```

It seems it wants to query too much info at once. The Font Awesome API has a dedicated page about this issue: https://fontawesome.com/docs/apis/graphql/complexity. Any thoughts?

**Comment by jefverme** [comment]
Same here, but without the upgrade of any packages. Worked fine yesterday

**Comment by aerni** [comment]
Looks like we'd have to simplify the query and request each family and style separately, and then merge the results to be used in the fieldtype. For now, just limit the styles in the fieldtype's config.

**Comment by jefverme** [comment]
@aerni this might be a stupid question, but how do I limit the styles?

**Comment by aerni** [comment]
In the fieldtype config when adding the field to your blueprint.

**Comment by jefverme** [comment]
Unfortunately that doesn't work. When loading the fieldtype in the CP the post request to {myDomain}/!/font-awesome/icons returns the same error :(

**Comment by aerni** [comment]
Oh yeah, makes sense. Feel free to submit a PR to fix the issue. I probably won't be getting to it for a while.

**Comment by aerni** [comment]
I found some time and took a closer look. Making this work most likely involves a major refactor. I don't quite know how to tackle it yet.

**Comment by ottz0** [comment]
> Same here, but without the upgrade of any packages. Worked fine yesterday

Same, can't access my pages in the control panel....500 error

**Comment by aerni** [comment]
Sadly, I currently have no way of resolving this issue. 

The culprit is Font Awesome's API. It doesn't provide a way to filter the icons by family and style. Which is why I'm currently fetching all the icons and grouping them by after the fact. This used to work fine until now. I'm not sure if Font Awesome changed their response limit or if they just added a lot more icons, and it's only now reaching the limit.

I reached out to Font Awesome's support and hope they'll have a solution.

The last resort would be to remove the feature that lets you choose the styles of the selectable icons.

**Comment by ottz0** [comment]
> Sadly, I currently have no way of resolving this issue.
> 
> The culprit is Font Awesome's API. It doesn't provide a way to filter the icons by family and style. Which is why I'm currently fetching all the icons and grouping them by after the fact. This used to work fine until now. I'm not sure if Font Awesome changed their response limit or if they just added a lot more icons, and it's only now reaching the limit.
> 
> I reached out to Font Awesome's support and hope they'll have a solution.
> 
> The last resort would be to remove the feature that lets you choose the styles of the selectable icons.

Thanks for keeping us up to date.....Maybe as a quick fix just have solid

**Comment by aerni** [comment]
That's not an option, as there is no way to just query one style. Also, many sites are relying on other styles as well.

**Comment by mlwilkerson** [comment]
This one's on me. I'm the Font Awesome developer who added some more stuff on complexity analysis recently. The motivation was to _improve the reliability_ of the service, by rejecting queries that could have been abusive and caused outages.

In my analysis, it was a little tricky to distinguish between abusive ones from legitimate ones like this. So I made a mistake in failing to account for this use case when setting the complexity limit.

We're in the process of increasing the complexity limit to allow for this, which I expect to be resolved soon (in a matter of hours). We also are looking more long-term toward how to provide better API access to the huge amount of Awesome that's yet to come.

**Comment by aerni** [comment]
Thank you, @mlwilkerson! Very much appreciate your swift response and excellent support! One more thing to love Font Awesome!
