### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by Oleafeon** [aerni/statamic-font-awesome#26]
Could you add the dark mode support

![Screenshot 2024-06-11 at 12 39 07](https://github.com/aerni/statamic-font-awesome/assets/20043831/fd4ef87c-1813-404e-8b5f-49d0c1eaf4ef)

**Comment by aerni** [comment]
Feel free to PR. Should be an easy copy-paste from Statamic's select fieldtype.

**Comment by Oleafeon** [comment]
i will do that tonight  
<img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDAyZGp2amJ0ZW41eXYwZGEzeTdhbTNvaXQxeHRhMWM5OWR6NWtiMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5wWf7GW1AzV6pF3MaVW/giphy.gif">
