### ISSUE TITLE
Statamic Font-Awesome missing in control panel after updating

### ISSUE THREAD

**Issue by Sennik** [aerni/statamic-font-awesome#29]
I recently have been updating Statamic (to 5.14.0) and statamic-font-awesome (to 3.0) and I am missing the font-awesome select field in my Dashboard. This is a site on which it already worked in the past.

1. I removed and required 3.0 with composer again, without any error's.
2. I removed and created the font-awesome field in the blueprint succesfully

further:

- {{ font_awesome:kit }} is in the header (Never been removed)
- The font-awesome.php config file is in /config
- The API token and kit are in the .env (They both checked out on font-awesome.com)

(These three never been deleted)

After this the field is still NOT visible in my Control Panel's SET where I used it, and where it worked flawlessly in the past. 

The field's Label is visible.

**Comment by aerni** [comment]
Thanks for reporting this issue. I just released a fix.
