### ISSUE TITLE
Icons don't load correctly in Chrome

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-font-awesome#5]
I can't select a basic cloud icon because there are so many cloud icons and the dropdown only shows so many. I can work around it by typing 'cloud (' but just thought this could be improved.

Awesome package btw!

**Comment by aerni** [comment]
What do you mean by `the dropdown only shows so many`? The dropdown should show all available icons. I came across issues with Chrome before. Maybe use another browser?

**Comment by stuartcusackie** [comment]
Yes through chrome there is a limited list of icons when you type in cloud, maybe about 20 or 30. It means that the basic 'fa-cloud' icon is not shown and all I can see are clouds with arrows.

I have uninstalled the package for now but I'll let you know if it's a chrome issue when I try again.

**Comment by aerni** [comment]
Ok, closing this for now.

**Comment by Oleafeon** [comment]
i have the same problem on chrome it only shows a couple of icons
look at the sidebar
![image](https://user-images.githubusercontent.com/20043831/169263255-19694c15-b718-49fb-b0a4-b52bedc0fa8a.png)

while on firefox you get alot more
![image](https://user-images.githubusercontent.com/20043831/169263552-f3909990-c5bd-47f2-a29d-eb67e88d0906.png)

**Comment by Oleafeon** [comment]
maybe make it so that the the one that you searched for is on top of the dropdown

**Comment by aerni** [comment]
Yeah, this is a known issue with Chrome. Hope to find a fix at some point. Feel free to PR a fix or use another browser for now.
