### ISSUE TITLE
Possible performance issues

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-font-awesome#6]
I have added the font awesome field to a field set which is part of a replicator, as well as in a couple of other replicator blocks. Control panel load times have gone from 2 seconds to about 15 seconds. I'm fairly certain it's the package causing the long delays as I have tried removing / re-adding the field.

No big deal for me, I can use a custom select field for now but I'll definitely try this again in future.

**Comment by aerni** [comment]
Are you using an SVG kit? There are known performance issues. You can work around it by using a Web Font kit instead. From the docs: `Note: If you are using a Font Awesome Kit with SVG as technology, you may run into performance issues when selecting icons. Change the technology to Web Font to speed things up.`

**Comment by stuartcusackie** [comment]
I've checked my kit and it is web font. I will come back if I find any more clues.

**Comment by aerni** [comment]
Ok, closing this for now.
