### ISSUE TITLE
Idea: custom values

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-font-awesome#7]
I have a couple of complex SVG icons that are not compatible with font awesome kits (e.g. the Livewire logo). I have to store these in my project as svg files. It would be great if I could add a custom value to this field, so within the dropdown there would be a value like 'icon-custom icon-livewire'. I could then use my own logic to render my custom svg.

Without this ability I would have to create three separate fields with conditional display logic:
- Icon type: select field: font awesome / custom
- Font awesome icon: statamic-font-awesome field
- Custom icon: a select field with my custom values

It would be great for me but I understand if you don't want to allow for this. Thanks for reading.

**Comment by aerni** [comment]
I don't think this should be part of this addon. However, I had pondered this idea before. The solution would be a new icons addon with different icon drivers such as Font Awesome, Heroicons, Streamline Icons, etc.
