### ISSUE TITLE
Missing API/Kit token should not throw an exception

### ISSUE THREAD

**Issue by dryven-dano** [aerni/statamic-font-awesome#8]
In my opinion, it is a bit harsh to throw an exception when booting the addon for a missing token to the Font Awesome API or a Font Awesome Kit. If so, this exception should only be thrown during development and only when the Font Awesome tag is used in a template. Otherwise, an info warning should be recorded in the log and simply no Font Awesome icon should be output.

**Comment by aerni** [comment]
Feel free to PR this change.
