### ISSUE TITLE
Wrong icon classnames, because the API kit returned an unresolved version

### ISSUE THREAD

**Issue by dryven-dano** [aerni/statamic-font-awesome#9]
There's a problem when using the addon with a specific kit, where the GraphQL returns a version of ``latest``, but the addon expects an acutal version string like ``5.1.0``. Therefore it uses the "fa-solid" syntax for classes instead of "fas" and none of the icons are displayed, as it can't find the class in the new kits' stylesheet.

Here's the response of the kit request to the API:

```json
{
    "token": "xxxxxxxxxx",
    "licenseSelected": "pro",
    "version": "latest",
    "iconUploads": {}
}
```

The tag tries to fetch the iconClass, but the condition doesn't take the case of "latest" into account in **FontAwesome.php** on Line 103:
```php
return Str::startsWith($this->kit()->get('version'), '5') ? 'fa' . substr($style, 0, 1) . ' fa-' . $icon : "fa-$style fa-$icon";
```

**Comment by aerni** [comment]
The case of `latest` is taken into account. If the version doesn't contain `5` it will use the new `fa-{style}` syntax. All versions after `5` use this new syntax.

**Comment by dryven-dano** [comment]
Please correct me if I'm wrong, but I just checked with the configuration and when I have "Latest 5.x" selected for my kit, the version I get from the API is also "latest", so it doesn't always resolve to 6.x, but also to 5.x. I just switched to "Latest 6.x" for this project, and it works now as expected. Can you reproduce my initial case?

**Comment by aerni** [comment]
I can't reproduce this. I suspect it's a caching issue. Whenever you change the config of a kit, you have to clear the Statamic cache.
